### ISSUE TITLE
Could not connect to container

### ISSUE THREAD

**Issue by regiszanandrea** [wernerwws/dynamodb-local-with-logging#1]
Hi, 

I started used your container but I can't connect to it
Here it's my container: 
```
CONTAINER ID   IMAGE                                   COMMAND                  CREATED              STATUS              PORTS                             NAMES
48e2d1b9e88f   wernerwws/dynamodb-local-with-logging   "java -jar DynamoDBL…"   About a minute ago   Up About a minute   8000/tcp                          dynamodb
```

When I run `$ aws dynamodb list-tables --endpoint-url http://localhost:8000`, I get: 

`Could not connect to the endpoint URL: "http://localhost:8000/"`

I tried too with -p option:
`$ docker run --name dynamodb -d wernerwws/dynamodb-local-with-logging -p 8000:8000`

But the container is restarting and it's not keep running

**Comment by wernerwws** [comment]
I think your docker run command has an issue perhaps you have to put `-p 80....` before the image name ...

```
docker run --help                                                               

Usage:	docker run [OPTIONS] IMAGE [COMMAND] [ARG...]
```

for me the following works:
```
➜  ~  docker run -d --name dynamodb -p 8000:8000 wernerwws/dynamodb-local-with-logging
3720277a0db67e52d3b7fc9e6dd4f4b0cc90b79e08d2c4e3ae7a097e4fb06ee0
➜  ~  aws --region us-east1 dynamodb list-tables --endpoint-url http://localhost:8000
{
    "TableNames": []
}
```
